[project]
name = "analyzer-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-core>=0.6.1",
    "autogen-ext[docker]>=0.6.1",
    "tiktoken>=0.9.0",
]
